# Generated by Django 6.0.2 on 2026-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_jobcard_client_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="custom_fields_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
