# Generated by Django 6.0.2 on 2026-02-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_jobcard_custom_fields_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="extra_fields",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
